# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('Fare', models.FloatField()),
                ('kilometres_driven', models.FloatField(blank=True, default=0)),
                ('car_type', models.CharField(max_length=200)),
                ('car_number', models.CharField(max_length=200)),
                ('has_ac', models.BooleanField()),
                ('capacity', models.IntegerField(default=1)),
                ('no_times_fined', models.IntegerField(default=0)),
                ('total_fines', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('create_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
        ),
    ]
