# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='kilometres_driven',
            new_name='kilometers_driven',
        ),
    ]
