# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20160926_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='Fare',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='no_times_fined',
            new_name='number_of_times_fined',
        ),
    ]
