# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20160926_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
