# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_at', models.DateField()),
                ('modified_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationDistances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('create_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='locations.Location')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='locations.Location')),
            ],
        ),
    ]
